### PR TITLE
Add ability to set current_dir

### PR DESCRIPTION
**Pull request by epage**
Some tests need to run in certain directories but if you call `std::env::set_current_dir` within your test, you can hit race conditions with other tests running at the same time.  This allows you to set the current_dir only on the child process.

### CODE REVIEW

**Comment by killercup** [comment]
Nice, thanks! Can you rebase this on master now that #24 has landed?

**Comment by epage** [comment]
btw this is how I resolved the unused_doc issues in another project

https://github.com/cobalt-org/cobalt.rs/commit/bd5d3b732a0bb50ec6e150956dcca9f3fb1b0914

**Comment by killercup** [comment]
Heh, thanks for the tip. Maybe updating error-chain would help as well ;)

Ed Page <notifications@github.com> schrieb am Fr. 8. Sep. 2017 um 15:18:

**Comment by killercup** [comment]
Thanks for this whole batch of PRs! I'm at a conference currently, so I'm only now able to review it. Looks great, though!

bors r+

**Comment by killercup** [comment]
bors r+

bors[bot] <notifications@github.com> schrieb am Mo. 11. Sep. 2017 um 12:20:

**Comment by killercup** [comment]
Huh, not sure what's bothering bors here. Maybe #33 and #35 can't be merged together?

**Comment by notriddle** [comment]
https://github.com/killercup/assert_cli/blob/master/.travis.yml#L27-L29

**Comment by notriddle** [comment]
You should probably allow Travis to build the `staging` branch.

**Comment by killercup** [comment]
Weird. How did it ever work before? Anyway, I'll try to fix it later when I
have some time

Michael Howell <notifications@github.com> schrieb am Mo. 11. Sep. 2017 um
19:01:

**Comment by killercup** [comment]
Okay, let's give it another try!

bors r+

**Pull request merged**
