### PR TITLE
Run and add rustfmt

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by killercup** [comment]
Let's wait for #46 before merging. Rebasing and reformatting this is trivial.

**Comment by Freyskeyd** [comment]
@killercup you can merge this PR, I will rebase mine ( #46 ) after that. 

I can also add coveralls to have more details about code coverage as well. 

here's an example of how it works with travis: https://github.com/Freyskeyd/Rundeck/blob/master/.travis.yml

**Comment by killercup** [comment]
Oh, I didn't realize the binaries were cached as well. Fine. Let's be clever.

@Freyskeyd, I removed coveralls in 9d81ed89c588f8f69d1f46d2d1e806b4e5a83e4b because the data wasn't very good. Maybe that changed?

**Comment by Freyskeyd** [comment]
@killercup Dunno if change, I didn't get any trouble.

**Comment by killercup** [comment]
You are welcome to add it again with the same tokens as in the linked commit and see if it's helpful :)

But in the meantime:

bors r+

**Pull request merged**
