### PR TITLE
Reduce needless recompiles

### PR DESCRIPTION
**Pull request by epage**
Build script calls skeptic which emits information asking cargo to
monitor content of README.md.skt.md for changes. If changes to that file
are detected cargo should rebuild this crate.  In case of this project
the files does not exist. This causes cargo to trigger a rebuild every
time in hope that it will get created by the build script.

The workaround is to create the file that skeptic asks to monitor which
stops cargo from triggering the rebuild.

For details consult this issues:

* budziq/rust-skeptic#25
* rust-lang/cargo#4213

### CODE REVIEW

**Comment by epage** [comment]
bors: +r

**Comment by epage** [comment]
bors: r+

**Comment by killercup** [comment]
Let me highjack this merged PR to thank you for releasing 0.5 and 0.5.1! <3

**Comment by epage** [comment]
You're welcome!

I'm curious, what do you see needing done before moving this to 1.0?  While I should get back to my regularly schedule project, I would like to also help work towards more crates hitting 1.0.

**Comment by killercup** [comment]
@epage good question! I'd like to make the arg parsing a bit leaner (cf. #25 and #32) and maybe improve the error output (#17, #18, #30).

My general goal is to make a library that makes writing tests like [these](https://github.com/killercup/waltz/tree/ef79bf0fc3cfc8dd225cce864e21a91192121afe/waltz_cli/tests) easy and fun. It'll probably involve generating some test boilerplate code, and I'm not entirely sure what I want that API to look like. I'm not even sure if that's in scope for assert_cli. What do you think?

**Pull request merged**
