### PR TITLE
Add `stdin` function

### LINKED ISSUE #26: Piping (stdin) to the process
Something like `AssertCli::command("cat").given_input(reader).prints(reader_as_string)`

cf. #21

### PR DESCRIPTION
**Pull request by sevagh**
Allows you to put the contents of a String in the program's stdin.

Fixes #26

### CODE REVIEW

**Comment by epage** [comment]
Looks great!

Two things
- Unsure about @killercup but I try to keep the commit history clean in my projects.  Unless killercup comes in and says otherwise, do you mind cleaning up the commits?
- Name.  As I said in #26,  I personally do not (yet) have opinions on the name (with_stdin, stdin, given_input).  Not sure if @killercup does.  I'd be willing to submit this as-is and release it, as long as the name is settled before 1.0 (#41).

**Comment by killercup** [comment]
> Unsure about @killercup but I try to keep the commit history clean in my projects. Unless killercup comes in and says otherwise, do you mind cleaning up the commits?

@killercup agrees and is in favor of squashes.

> Name.

Hmmm. Do we have an existing pattern? Do the API guidelines give us a pattern to use?

**Comment by sevagh** [comment]
I'll squash the commits. I was more curious about other feedback, i.e. is a `String` OK? I tried something with a `Read` trait but that involves either boxes or lifetimes and the change became too intrusive.

**Comment by epage** [comment]
I'm not seeing anything in the [naming guidelines](https://rust-lang-nursery.github.io/api-guidelines/naming.html) that might apply.

[`Command`](https://doc.rust-lang.org/std/process/struct.Command.html) configures through
- `stdin`
- `stdout
- `stderr`

For assert_cli, we cuerrently have
- `stdout`
- `stderr`

So if we consider that precedence, then the name would be just `stdin`.  Overall, I'm not seeing a big deciding factor in any direction.

**Comment by sevagh** [comment]
I renamed it to `stdin()` and squashed the commits.

**Comment by sevagh** [comment]
Also not sure if I should be running `cargo fmt` - it makes a lot of changes in files I haven't touched.

**Pull request merged**
